# **Gunshot deaths in the US**

## **Load data**

In [16]:
import numpy as np
import pandas as pd
import csv
import matplotlib.pyplot as plt
%matplotlib inline

### Without pandas

In [15]:
GUNSHOT_DATA_PATH = './data/interactive_data.csv'

gunshots_data = []
header = []
with open(GUNSHOT_DATA_PATH, 'r') as gunshots_file:
    csvreader = csv.reader(gunshots_file)
    header = next(csvreader)
    for line in csvreader:
        gunshots_data.append(line)

print(header)
print(gunshots_data[0])

['', 'Intent', 'Gender', 'Age', 'Race', 'Deaths', 'Population', 'Rate']
['1', 'None selected', 'None selected', 'None selected', 'None selected', '33599', '316299978', '10.6']

### With pandas

In [82]:
GUNSHOT_DATA_PATH = './data/interactive_data.csv'

gunshots_data = pd.read_csv(GUNSHOT_DATA_PATH)
gunshots_data

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
0,1,None selected,None selected,None selected,None selected,33599,316299978,10.6
1,2,None selected,None selected,None selected,White,22079,197369634,11.2
2,3,None selected,None selected,None selected,Black,7765,38896382,20.0
3,4,None selected,None selected,None selected,Hispanic,3007,54049078,5.6
4,5,None selected,None selected,None selected,Asian/Pacific Islander,442,16315561,2.7
...,...,...,...,...,...,...,...,...
535,536,Unknown,Male,5,White,0,0,NaN
536,537,Unknown,Male,5,Black,0,0,NaN
537,538,Unknown,Male,5,Hispanic,0,0,NaN
538,539,Unknown,Male,5,Asian/Pacific Islander,0,0,NaN
539,540,Unknown,Male,5,Other,0,0,NaN

## **Statistics**

### **Suicide rates**

In [85]:
gunshots_data_clean_intent = gunshots_data.query("Intent != 'None selected'") # clean data for intent

nb_deaths = gunshots_data_clean_intent['Deaths'].sum()
suicides_data = gunshots_data_clean_intent.query("Intent == 'Suicide'")
nb_suicides = suicides_data['Deaths'].sum()

print(nb_deaths)
print(nb_suicides)
suicides_data

268789
168464

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
108,109,Suicide,None selected,None selected,None selected,21058,316299978,6.7
109,110,Suicide,None selected,None selected,White,18457,197369634,9.4
110,111,Suicide,None selected,None selected,Black,1111,38896382,2.9
111,112,Suicide,None selected,None selected,Hispanic,1057,54049078,2.0
112,113,Suicide,None selected,None selected,Asian/Pacific Islander,248,16315561,1.5
...,...,...,...,...,...,...,...,...
211,212,Suicide,Male,5,White,1,0,inf
212,213,Suicide,Male,5,Black,0,0,NaN
213,214,Suicide,Male,5,Hispanic,0,0,NaN
214,215,Suicide,Male,5,Asian/Pacific Islander,0,0,NaN
215,216,Suicide,Male,5,Other,0,0,NaN

In [84]:
print("%.1f%% of gunshot deaths in the US are suicides" % (100*nb_suicides/nb_deaths))

62.7% of gunshot deaths in the US are suicides

### **Male proportion of suicides**

In [89]:
suicides_data_clean_gender = suicides_data.query("Gender != 'None selected'") # clean data for gender
nb_suicides = suicides_data_clean_gender['Deaths'].sum()

male_suicides = suicides_data_clean_gender.query("Gender == 'Male'")
nb_male_suicides = male_suicides['Deaths'].sum()

print(nb_male_suicides)
print(nb_suicides)
male_suicides

72646
84233

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
180,181,Suicide,Male,None selected,None selected,18162,155631868,11.7
181,182,Suicide,Male,None selected,White,15852,97207346,16.3
182,183,Suicide,Male,None selected,Black,989,18533996,5.3
183,184,Suicide,Male,None selected,Hispanic,941,27378155,3.4
184,185,Suicide,Male,None selected,Asian/Pacific Islander,215,7726442,2.8
185,186,Suicide,Male,None selected,Other,164,4785929,3.4
186,187,Suicide,Male,Under 15,None selected,114,31249189,0.4
187,188,Suicide,Male,Under 15,White,98,16182922,0.6
188,189,Suicide,Male,Under 15,Black,6,4228176,0.1
189,190,Suicide,Male,Under 15,Hispanic,9,7664425,0.1
190,191,Suicide,Male,Under 15,Asian/Pacific Islander,2,1431715,0.1
191,192,Suicide,Male,Under 15,Other,0,1741952,0.0
192,193,Suicide,Male,15 - 34,None selected,4399,44017869,10.0
193,194,Suicide,Male,15 - 34,White,3339,24831032,13.4
194,195,Suicide,Male,15 - 34,Black,466,5869943,7.9
195,196,Suicide,Male,15 - 34,Hispanic,424,9379683,4.5
196,197,Suicide,Male,15 - 34,Asian/Pacific Islander,92,2415040,3.8
197,198,Suicide,Male,15 - 34,Other,78,1522171,5.1
198,199,Suicide,Male,35 - 64,None selected,8991,60810870,14.8
199,200,Suicide,Male,35 - 64,White,8005,40585343,19.7
200,201,Suicide,Male,35 - 64,Black,411,6915685,5.9
201,202,Suicide,Male,35 - 64,Hispanic,405,8914219,4.5
202,203,Suicide,Male,35 - 64,Asian/Pacific Islander,99,3129535,3.2
203,204,Suicide,Male,35 - 64,Other,71,1266087,5.6
204,205,Suicide,Male,65+,None selected,4656,19553940,23.8
205,206,Suicide,Male,65+,White,4409,15608050,28.2
206,207,Suicide,Male,65+,Black,106,1520192,7.0
207,208,Suicide,Male,65+,Hispanic,104,1419828,7.3
208,209,Suicide,Male,65+,Asian/Pacific Islander,22,750151,2.9
209,210,Suicide,Male,65+,Other,14,255719,5.5
210,211,Suicide,Male,5,None selected,2,0,inf
211,212,Suicide,Male,5,White,1,0,inf
212,213,Suicide,Male,5,Black,0,0,NaN
213,214,Suicide,Male,5,Hispanic,0,0,NaN
214,215,Suicide,Male,5,Asian/Pacific Islander,0,0,NaN
215,216,Suicide,Male,5,Other,0,0,NaN

In [90]:
print("%.1f%% of gunshot suicide victims are male" % (100*nb_male_suicides/nb_suicides))

86.2% of gunshot suicide victims are male

### **Homicide rates**

In [92]:
homicides_data = gunshots_data_clean_intent.query("Intent == 'Homicide'")
nb_homicides = homicides_data['Deaths'].sum()

homicides_data

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
216,217,Homicide,None selected,None selected,None selected,11726,316299978,3.7
217,218,Homicide,None selected,None selected,White,3049,197369634,1.5
218,219,Homicide,None selected,None selected,Black,6503,38896382,16.7
219,220,Homicide,None selected,None selected,Hispanic,1878,54049078,3.5
220,221,Homicide,None selected,None selected,Asian/Pacific Islander,186,16315561,1.1
...,...,...,...,...,...,...,...,...
319,320,Homicide,Male,5,White,2,0,inf
320,321,Homicide,Male,5,Black,0,0,NaN
321,322,Homicide,Male,5,Hispanic,0,0,NaN
322,323,Homicide,Male,5,Asian/Pacific Islander,0,0,NaN
323,324,Homicide,Male,5,Other,0,0,NaN

In [93]:
print("%.1f%% of gunshot deaths in the US are homicides" % (100*nb_homicides/nb_deaths))

34.9% of gunshot deaths in the US are homicides

### **Young black men victims of homicides**

In [101]:
homicides_data_clean_agr = homicides_data.query("Gender == 'Male' & Age == '15 - 34' & Race != 'None selected'") # clean data for age, gender and race
nb_ym_homicides = homicides_data_clean_agr['Deaths'].sum()

black_data = homicides_data_clean_agr.query("Race == 'Black'")
nb_black = black_data['Deaths'].sum()

print(nb_black)
print(nb_ym_homicides)
black_data

4312
6521

     Unnamed: 0    Intent Gender      Age   Race  Deaths  Population  Rate
302         303  Homicide   Male  15 - 34  Black    4312     5869943  73.5

In [103]:
print("%.1f%% of the young men victims of homicide are black" % (100*nb_black/nb_ym_homicides))

66.1% of the young men victims of homicide are black

### **Women victim of homicide**

In [105]:
homicides_data_clean_gender = homicides_data.query("Gender != 'None selected'")
nb_homicides = homicides_data_clean_gender['Deaths'].sum()

women_data = homicides_data_clean_gender.query("Gender == 'Female'")
nb_women = women_data['Deaths'].sum()

print(nb_women)
print(nb_homicides)

women_data

7167
46906

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
252,253,Homicide,Female,None selected,None selected,1791,160668110,1.1
253,254,Homicide,Female,None selected,White,860,100162288,0.9
254,255,Homicide,Female,None selected,Black,633,20362385,3.1
255,256,Homicide,Female,None selected,Hispanic,232,26670924,0.9
256,257,Homicide,Female,None selected,Asian/Pacific Islander,47,8589119,0.5
257,258,Homicide,Female,None selected,Other,20,4883395,0.4
258,259,Homicide,Female,Under 15,None selected,85,29836679,0.3
259,260,Homicide,Female,Under 15,White,38,15355910,0.2
260,261,Homicide,Female,Under 15,Black,27,4095428,0.7
261,262,Homicide,Female,Under 15,Hispanic,19,7330024,0.3
262,263,Homicide,Female,Under 15,Asian/Pacific Islander,1,1393440,0.1
263,264,Homicide,Female,Under 15,Other,1,1661877,0.1
264,265,Homicide,Female,15 - 34,None selected,815,42593280,1.9
265,266,Homicide,Female,15 - 34,White,267,23942099,1.1
266,267,Homicide,Female,15 - 34,Black,389,6023846,6.5
267,268,Homicide,Female,15 - 34,Hispanic,131,8580577,1.5
268,269,Homicide,Female,15 - 34,Asian/Pacific Islander,16,2535358,0.6
269,270,Homicide,Female,15 - 34,Other,13,1511400,0.9
270,271,Homicide,Female,35 - 64,None selected,733,63125058,1.2
271,272,Homicide,Female,35 - 64,White,426,41284839,1.0
272,273,Homicide,Female,35 - 64,Black,199,7932606,2.5
273,274,Homicide,Female,35 - 64,Hispanic,76,8863203,0.9
274,275,Homicide,Female,35 - 64,Asian/Pacific Islander,26,3668172,0.7
275,276,Homicide,Female,35 - 64,Other,6,1376239,0.4
276,277,Homicide,Female,65+,None selected,158,25113094,0.6
277,278,Homicide,Female,65+,White,129,19579439,0.7
278,279,Homicide,Female,65+,Black,18,2310506,0.8
279,280,Homicide,Female,65+,Hispanic,6,1897119,0.3
280,281,Homicide,Female,65+,Asian/Pacific Islander,4,992150,0.4
281,282,Homicide,Female,65+,Other,1,333879,0.3
282,283,Homicide,Female,5,None selected,0,0,NaN
283,284,Homicide,Female,5,White,0,0,NaN
284,285,Homicide,Female,5,Black,0,0,NaN
285,286,Homicide,Female,5,Hispanic,0,0,NaN
286,287,Homicide,Female,5,Asian/Pacific Islander,0,0,NaN
287,288,Homicide,Female,5,Other,0,0,NaN

In [106]:
print("%.1f%% of the homicide victims are women" % (100*nb_women/nb_homicides))

15.3% of the homicide victims are women